name: visitors_and_grievance_application
description: ""

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  carousel_slider: ^5.0.0
  uuid: ^4.5.1
  supabase_flutter: ^2.8.4
  platform: ^3.1.6
  universal_platform: ^1.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  url_launcher: ^6.3.0
  file_picker: ^10.3.2
  # flutter_sms: ^2.3.3
  # telephony: ^0.2.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"


flutter:


  uses-material-design: true

 
  assets:
    - assets/
  